# Generated by Django 5.1.3 on 2024-11-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.DateTimeField()),
                ('sintomas_apresentados', models.TextField(max_length=500)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
            ],
        ),
    ]
