# Generated by Django 5.1.3 on 2024-11-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_hora_consulta_horario_remove_consulta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedio', models.CharField(max_length=50)),
                ('dosagem', models.CharField(max_length=4)),
                ('qtd_de_dias', models.CharField(max_length=3)),
                ('qtd_por_dia', models.CharField(max_length=2)),
            ],
        ),
    ]
